name: Linter Runner

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  linter:
    name: Run linter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run ruff
        run: ruff check . --config=ruff.toml

      - name: Run mypy
        run: mypy --strict .
  tests:
    name: Run tests with Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run demos tests with Python ${{ matrix.python-version }}
        run: |
          env HAMMETT_SETTINGS_MODULE=demos.admin_panel_bot.settings python3 demos/admin_panel_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.clicker_bot.settings python3 demos/clicker_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.dynamic_keyboard_bot.settings python3 demos/dynamic_keyboard_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.hide_keyboard_bot.settings python3 demos/hide_keyboard_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.multi_state_bot.settings python3 demos/multi_state_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.paywall_bot.settings TOKEN=test-token python3 demos/paywall_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.quiz_bot.settings TOKEN=test-token python3 demos/quiz_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.reminder_bot.settings python3 demos/reminder_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.say_hello_bot.settings python3 demos/say_hello_bot/tests.py
          env HAMMETT_SETTINGS_MODULE=demos.simple_jump_bot.settings python3 demos/simple_jump_bot/tests.py

      - name: Run Hammett tests with Python ${{ matrix.python-version }}
        run: |
          env HAMMETT_SETTINGS_MODULE=tests.settings coverage run -m unittest discover -s tests/
          coverage report
